name: HBAProject
version: ${project.version}
main: hbaproject.hbaproject.HBAProject
api-version: 1.16
authors: [ Hyunsol ]
description: HBAProject Plugin
depend: [ProtocolLib]
commands:
  helloworld:
  hba-region:
  hba-an: